const TEN_MINUTES = 600000;
const ONE_MINUTE = 60000;
const LONG_SHOTCLOCK = 24000;
const SHORT_SHOTCLOCK = 14000;
const FIVE_SECOND = 5000;
const ONE_SECOND = 1000;
const INTERVAL_MS = 100;

export {
    TEN_MINUTES,
    ONE_MINUTE,
    LONG_SHOTCLOCK,
    SHORT_SHOTCLOCK,
    FIVE_SECOND,
    ONE_SECOND,
    INTERVAL_MS
};