const assistTypes = [
    'none',
    'bouncepass',
    'chestpass',
    'overheadpass',
    'lobpass',
    'noLookPass',
    'behindTheBack',
    'wrapAround',
    'alleyoop',
    'handoff',
    'dribbleHandoff',
    'inbound',
    'outlet',
    'skip',
    'touch',
    'postEntry',
    'pickAndRoll',
    'cut',
    'backdoor',
    'screen',
    'pick',
    'roll',
    'pop',
    'fade',
    'slip',
    'flare',
    'pin',
    'seal',
    'dive',
    'spotUp',
    'relocate',
    'rebound',
    'foul',
    'block'
];    

module.exports = assistTypes